### PR TITLE
set stack type only after successful retrieval

### LINKED ISSUE #1271: Autocrafting voids items
looks like there is issue when 2 receipts depends on each another:
image

image

above 2 are precessing in single machine: 

image

image

image

now if i request 12 resistors it sends items, craft it and extract 12 and at same time try insert, but it never enter machine, item is lost

### PR DESCRIPTION
**Pull request by mikiones**
don't void items please, fix #1271

### CODE REVIEW

**Comment by davboecki** [comment]
For this PR goes the same thing as your other one. ItemStacks should not be null. 

To rework this, set outputStack to an empty itemstack and not null, use a isEmpty check on outputStack and then you should not need the getCount check, which by the way should have been an negated isEmpty check by the way.

**Comment by mikiones** [comment]
it stills return null, should this be changed to ItemStack.Empty ?

**Comment by davboecki** [comment]
Please use .isEmpty(). And the other question I need to check, but generally it should return ItemStack.Empty. But if it does not at the moment, then If you change it please check every caller to see if it handels it correctly

**Comment by mikiones** [comment]
looks like everything assume null = ItemStack.EMPTY

**Comment by mikiones** [comment]
created another issue for that(#1277 ). as this is bug fix.

**Comment by bziemons** [comment]
This change is not sufficient. Changing this (which is correct and will fix bugs, but will introduce new bugs), requires to change all `IInventoryUtil` implementations to never return `null` and all usages of those implementation to use `.isEmpty` checks.

**Comment by mikiones** [comment]
Have PR in draft for that. The issue there is that it deletes items. So trying get fix for that first .

**Pull request closed without merging**
