### PR TITLE
port to BuildCraft 7

### PR DESCRIPTION
**Pull request by asiekierka**

### CODE REVIEW

**Comment by asiekierka** [comment]
If you need any API additions, or internal code refactors, poke me soon and I still can do slightly breaking changes while 7 is in beta.

**Comment by SonOfTheStars** [comment]
Your awesome asie :D Allready looking forward to the Changelog of BC7.x

**Comment by davboecki** [comment]
@theZorro266 can you merge this into a new branch?

**Comment by bziemons** [comment]
~~@davboecki I tried, but I didn't get it to work. buildcraft-7.0.1-dev.jar is built and uploaded though.~~

Actually it did work and I didn't even recognize it.. I feel kindof dumb.

See https://github.com/RS485/LogisticsPipes/tree/mc17-0.9-bc7
Other than that it is not compilable right now.

**Pull request closed without merging**
