### PR TITLE
Issue #906: Fix for ClassNotFoundException in ForestryProxy

### PR DESCRIPTION
**Pull request by joral**
Corrected package name when loading the Forestry TileAnalyzer

### CODE REVIEW

**Comment by SonOfTheStars** [comment]
@joral Sadly, the devs currently are unavailabl. Your PR will need to wait until someone takes Over or the devs return

**Comment by joral** [comment]
Well, I don't think I'd be ready to take over. It's a mod I use, so I'd like to see it maintained. I figured I'd start using open bug reports to start learning the code.

**Comment by SonOfTheStars** [comment]
@joral for now, you can PR further workings of yours [Here](https://github.com/Bitterholz/LogisticsPipes).
Thats my ongoing Copy of LP wich im working on.

**Comment by loordgek** [comment]
@Bitterholz can you join the @485 team ??

**Pull request merged**
