### PR TITLE
Fix missed recipe(s) for Crafting Cleanup Upgrade (works)

### PR DESCRIPTION
**Pull request by chaos234**
Well, after a few mor tries it has worked now so only the part is shown which was added/edited/removed.

Referenced Error: #710

### CODE REVIEW

**Comment by SonOfTheStars** [comment]
There is actually a big mistake there. The Code for Crafting is split into standart and Beta Recipes. Beta Recipes do no longer use any Chipsets from BC since LP wants to get Independant.

This basicly mans you need to adapt the following Lines in your Code towards Using the Beta Items:
https://github.com/RS485/LogisticsPipes/pull/715/files#diff-27bb48fea3d47dd0f7f5295f5a5a34dfR1887 and https://github.com/RS485/LogisticsPipes/pull/715/files#diff-27bb48fea3d47dd0f7f5295f5a5a34dfR1899 and https://github.com/RS485/LogisticsPipes/pull/715/files#diff-27bb48fea3d47dd0f7f5295f5a5a34dfR1911

Towards using The Items defined here:
https://github.com/RS485/LogisticsPipes/blob/dev/common/logisticspipes/items/ItemPipeComponents.java

Please don't just copy-pasta

**Comment by chaos234** [comment]
Thanks for your replay, I'll look at and change the it.

Must I made a new pullrequest and close this one?

**Comment by SonOfTheStars** [comment]
You can just push your Changes and the PR will recognize them and add them automaticlly.

**Comment by bziemons** [comment]
Closed, because the requested changes were not made.

**Pull request closed without merging**
