### PR TITLE
Add shared project config

### PR DESCRIPTION
**Pull request by bziemons**
@davboecki @therealfarfetchd can you two test if integrating these configs work for you and if the .gitignore is complete? I think the best way is to close your IDE, go into command-line, move your `.idea` folder out, update the working directory with `git fetch && git checkout add-shared-project-config` and then copy the `.idea` folder back in and override any files. Then look what `git status` says and open your IDE (might need an *invalidate cache and restart*) to see if that worked out.

This has several advantages for use with IDEA:
* annotation processing is on by default
* code style is provided by default
* copyright notice in `network.rs485` package is committed and added by default
* other configurations may be shared in the future

If you have anything to add, feel free to commit and push to this branch. Otherwise just give your O.K.

### CODE REVIEW

**Comment by dblsaiko** [comment]
I don't have an `.idea` folder, but I searched for some of the lines of the file ` .idea/codeStyles/Project.xml` in the patch and it seems like that's the same file as `LogisticsPipes.ipr` in my workspace (and I doubt that this patch will work for that reason). Also iirc adding the workspace folder to the git repo is a bad thing, I think IDEA has an option for importing/exporting code style though.

**Comment by bziemons** [comment]
Ah okay, you have a file-based project, but then it just ignores the .idea folder, I think. I would recommend switching to a directory-based project though. I don't know what you mean with workspace folder though? The whole .idea folder?

EDIT: See https://intellij-support.jetbrains.com/hc/en-us/articles/206544839-How-to-manage-projects-under-Version-Control-Systems

**Comment by dblsaiko** [comment]
Yeah, the .idea folder (or *.i?? files).

Apparently it's only part of that that you're not supposed to put in VCS, that's cool then

**Comment by dblsaiko** [comment]
Opening the existing project and then setting it up as a gradle project through the notification makes it complain that the project JDK is not set, so you have to do that manually which is a bit of a hassle. And you can't import it as a gradle project directly since it'll delete all the custom settings. 

Had to set the project output path (as with the SDK above) manually, I guess because opening the project files are incomplete, but still there, and it doesn't populate the default values if they aren't set.

Also genIntellijRuns doesn't do anything now, but I guess that's more because of the folder based format as opposed to having the settings in VCS. So I had to create the run tasks manually

IMO in the current state it's a bigger headache than before. I'd just provide importable preset files. Or of course, if there's a way to make it work automatically, I won't complain ;)
Like this, it's not practical since you can't just "import and go", like with everything else.

**Comment by loordgek** [comment]
can we use gradle magic ?
http://mrhaki.blogspot.com/2016/03/gradle-goodness-enable-compiler.html

**Comment by bziemons** [comment]
@therealfarfetchd first of all thanks for your valuable feedback :+1: 

I definitely did not expect to see users of the .ipr format. davboecki did use that until now as well, which I was not aware of. It seems to be deprecated though. `genIntellijRuns` has always worked for me together with the .idea folder project.

I have made a few adjustments. I added the `misc.xml`, because that contains the default JDK level to use. Along with the project output directory. I guess it was ignored, because of this https://stackoverflow.com/questions/26363025/gitignore-misc-xml-and-iml-with-android-studio-0-8-9 -- that shouldn't be an issue with LP though.

Also I added shared run configurations. `genIntellijRuns` seems to miss setting the module of the generated run configurations nowadays. At least those shared configs do a better job at that + you can always make a copy and still configure your own personal run configs.

I have now tried several times with different project folder names and fresh git clones and it seems to be much better now. Could you give this a try again @therealfarfetchd ?

@loordgek I try not to rely on too many build tools at once or too many dependencies, because of my experience with many different tools at once. Thanks for the heads-up though. If this change is accepted, it would not be needed anyway though.

**Pull request closed without merging**
