### PR TITLE
skip empty slots in quick sort don't try to route empty items.

### PR DESCRIPTION
**Pull request by mikiones**
posible fix for #1261

### CODE REVIEW

**Comment by bziemons** [comment]
I don't think slot can be null anymore. What do you think @davboecki ?

**Comment by mikiones** [comment]
in debugger is allways air with isEmpty = true

**Comment by dblsaiko** [comment]
Yes, item stacks are never null in 1.12. (And if they are, that's a bug.)

**Comment by mikiones** [comment]
skip then null check ?

**Comment by davboecki** [comment]
Like zorro and realfarfetchd said ItemStacks should not be null anymore. So yes please remove the null check and only use the isEmpty

**Comment by mikiones** [comment]
nvm

**Pull request closed without merging**
