### PR TITLE
Create de_DE.lang

### PR DESCRIPTION
**Pull request by Vexatos**
Crowdin is outdated (as expected). Better stick to a working system and do it here.
On Crowdin, I cannot change a translation without others voting on it, and so far noone but me ever voted on anything. Guess why.

### CODE REVIEW

**Comment by bziemons** [comment]
I would rather create a new repository and give frequent translators, like you are, commit permissions.
Also we should talk about the license, because right now the copyright of language files is not clear.

**Comment by Vexatos** [comment]
That's the way many mods choose, e.g. Railcraft or BuildCraft. Just set it up as a git submodule and managing becomes easy. License should definitely be some very open one.

**Comment by davboecki** [comment]
https://github.com/RS485/LogisticsPipes-Language/commit/c2ba9f17ae8b30f3d6a26cf573a2640520fcffc0

**Comment by hron84** [comment]
I'm really thinking on making a Hungarian translation if I have a free time and if you want it.

**Comment by davboecki** [comment]
Translations are always good. if you want to provide them, just make a PR to: https://github.com/RS485/LogisticsPipes-Language

**Pull request closed without merging**
