### PR TITLE
Various changes

### PR DESCRIPTION
**Pull request by MrTJP**

### CODE REVIEW

**Comment by MrTJP** [comment]
hmmm, which conflicts need to be solved?

**Comment by davboecki** [comment]
You need to rebase your Dev branch with the LP-Dev branch.

**Comment by MrTJP** [comment]
i dont know what i did, but i solved conflicts and merged the current dev into my dev.  now, it will let you pull it hopefully :)

**Comment by davboecki** [comment]
Looks good. Will pull that as soon as i can get in contact to Azanor to ask for permission.

**Pull request merged**
