### PR TITLE
Start proper 1.7 port work

### PR DESCRIPTION
**Pull request by asiekierka**

### CODE REVIEW

**Comment by davboecki** [comment]
Before there is more work done on this, someone should update to the newest mc16 version.

**Comment by asiekierka** [comment]
Isn't the only new thing in it TE3 support which is invalid for now anyway?

**Comment by davboecki** [comment]
Yes and no, it's for TE3 but it lays a lot of ground work for future support for other pipe systems other than BC. And invalid doesn't mean that it can't be restored.

**Comment by asiekierka** [comment]
Right. In that case, it should be merged in as soon as possible.

**Comment by davboecki** [comment]
I've made a backup of this PR. But I'm not going to merge this because I don't want to move the source files around. So I can work with 1.6 and 1.7 at the same time (hoptefully).

**Comment by GUIpsp** [comment]
@davboecki you can still work with both if you move source files around

**Comment by davboecki** [comment]
Only if git recognized every file that has been moved. And that is not guaranteed if you don't use git to move them. And not moving them also makes it easier.

**Comment by GUIpsp** [comment]
> Only if git recognized every file that has been moved. And that is not guaranteed if you don't use git to move them.

git doesn't track moves, it tracks deletions and creations

> And not moving them also makes it easier. 

Can't disagree with this.

**Pull request closed without merging**
