### PR TITLE
Never passively route to craftingModule

### LINKED ISSUE #1255: output of crafting card is routed to inventory where chases pipe is connected too
image

one of the crafting cards is 
image

all glass now is routed to that inv. 

image

seams to happend to random card but only one a time,

### PR DESCRIPTION
**Pull request by mikiones**
fixes #1255

### CODE REVIEW

**Comment by bziemons** [comment]
I think passively routing to crafting modules/pipes is a good thing. If there is a bug in detecting *what* should be requested, that requires a different solution

**Comment by mikiones** [comment]
should then it check if the itemStack is one of from receipte and if it is in crafting before route it to slot?

**Comment by mikiones** [comment]
not sure if WaitingForCrafting is indeed what i think it is.

**Comment by davboecki** [comment]
https://github.com/RS485/LogisticsPipes/commit/409c47644924d57ffbece082c4b7ee3369b162c4

**Pull request closed without merging**
