### PR TITLE
Better addon interfacing for modules

### PR DESCRIPTION
**Pull request by Bubbet**

### CODE REVIEW

**Comment by davboecki** [comment]
Why go this strange array route and not just make it two functions? One without the last parameter calling the one with the last parameter and LP's mod ID as the last parameter. And the one with the modID as a parameter

**Comment by Bubbet** [comment]
That was a thought that crossed my mind. I don't know why i chose this way, do you think i should have done it the other way?

**Comment by davboecki** [comment]
I think the other way is better because it exactly states what parameters the function expects. In the current way, one could assume it accepts multiple mod ids which just is not the case.

**Comment by Bubbet** [comment]
Alright, do you want to close this pull request and i'll start another with that other method?

**Comment by davboecki** [comment]
Just do it in this PR like you did.

Why not just call the method with ModID = LP instead of having duplicate code?

**Comment by Bubbet** [comment]
I don't know if i get what you're saying with that.

**Comment by davboecki** [comment]
I mean like this: 
```java
public static <T extends Item> T setName(T item, String name) {
	return setName(item, name, LPConstants.LP_MOD_ID);
}
```

**Comment by Bubbet** [comment]
That is nicer.

**Comment by davboecki** [comment]
And maybe: 
```java
public static void registerModule(IForgeRegistry<Item> registry, String name, @Nonnull Supplier<? extends LogisticsModule> moduleConstructor) {
	registerModule(registry, name, moduleConstructor, LPConstants.LP_MOD_ID);
}
```
?

**Comment by Bubbet** [comment]
Sorry, i really don't have a whole lot of experience.

**Comment by davboecki** [comment]
No worries. I was in your position at some point and learned a lot through different people working on LP.

**Comment by Bubbet** [comment]
Well i hope to learn lots more here too.

**Pull request merged**
