### PR TITLE
Refactor

### PR DESCRIPTION
**Pull request by dblsaiko**
So, this PR does a lot of stuff (might have gotten a little bit out of hand):
 - Item/Block names consistency. They are now consistent with the registry names from other mods, and texture names, model paths, language keys, etc. are now all derived from the registry name in case they weren't before
 - Don't register models at the same time as registering items, there's an event for that.
 - Partially converted recipes to data files (also wrote a neat recipe exporter for that, which is still in the code but not called)
 - No longer take the class name as registry name for some stuff, to allow renaming classes, and have sensible names for items
 - Moved item/block fields to LPItems/LPBlocks, and use ObjectHolder annotations to assign them instead of assigning them when creating the items initially.
 - Fixed some localization entries
 - DataFixer/events to keep compatibility and fix registry names from older builds
 - registerModels in the item class is bad. No more registerModels in the item class. Instead, register them in a central place, for all items. (`ClientProxy#registerModels()`)
 - Less reflection for instantiation, instead use method references (`SomeClass::new` instead of `SomeClass.class`)
 - Update to use current resource pack version 3 (en_US.lang -> en_us.lang)
 - Remove some unused textures

And everything still works as before! I hope. At least from my tests, it does.

### CODE REVIEW

**Review by davboecki — DISMISSED** [review]
Looks good to me. Only one problem I found, was that the comment in the logistics programmer tooltip is no longer translated, but that's due to the missing ".name" at the end of the unlocalizedName.

**Comment by dblsaiko** [comment]
Whoops, my bad.

**Comment by davboecki** [comment]
And you forgot to change the resourcePath equals in line 49 FluidContainerRenderer.java. it would be "fluid_container".

**Review by davboecki — CHANGES_REQUESTED** [review]
And you forgot to change the resourcePath equals in line 49 FluidContainerRenderer.java. it would be "fluid_container".

**Review by davboecki — APPROVED** [review]

**Pull request merged**
