### PR TITLE
Remove unnecessary copying of EnumSets in ServerRouter

### PR DESCRIPTION
**Pull request by TheLoneWolfling**
Mitigates #640. Note: there are some other low-hanging fruit here, but
they require more changes to the routing logic than I am comfortable
with doing.

### CODE REVIEW

**Comment by bziemons** [comment]
@davboecki looks good to me, also seems stable enough for 0.8

**Comment by SonOfTheStars** [comment]
Seems great!

**Comment by davboecki** [comment]
@theZorro266 can you merge this into 0.9

**Comment by bziemons** [comment]
done.

**Pull request merged**
