### PR TITLE
Travis CI

### PR DESCRIPTION
**Pull request by keplersj**
I got LogisticsPipes to build with Travis CI. Don't believe me? Look here: https://travis-ci.org/k2b6s9j/LogisticsPipes-Dev

### CODE REVIEW

**Comment by GUIpsp** [comment]
We already have jenkins

**Comment by keplersj** [comment]
You can think of it like a backup. In case Zorro's server ever goes down.

**Comment by davboecki** [comment]
I tryed adding Travis myself but i couldn't get astyle to run. That's what the test target was for. I will probably add this but not as a backup. It will be there to precompile PR's and see if they could cause any compile errors. The test target doesn't generate a jar file so there will be no result jar on Travis only a status message.
Oh and maybe you could redo this in one commit so that there aren't 6 commits for adding one single file.

**Comment by keplersj** [comment]
Of course. I'll do it when I get home today. Should I do it on this branch?
—

**Comment by davboecki** [comment]
On this branch is fine.

**Comment by keplersj** [comment]
Please ignore this. Better version is in #36.

**Pull request closed without merging**
