### PR TITLE
fix bc gate triggers 

### PR DESCRIPTION
**Pull request by noah13245678**
(this is my first time using github, sorry if i'm doing something wrong)

### CODE REVIEW

**Comment by davboecki** [comment]
Could you please squash your commits and maybe say something as to why this change is required?

**Comment by AEnterprise** [comment]
@davboecki github can squash commits when merging for you

**Comment by noah13245678** [comment]
If you squash the commits for me that be great. I'm just starting to use github now and I don't know how to do that. 

I'd like this change because, for registering buildcraft gate triggers (pipe waiting for crafting, supply failed, etc) it currently checks if the IStatementContainer object is an instanceof LPBCPipe, but with the current buildcraft api it is always a buildcraft.transport.Gate, so the triggers are never added. Checking the type of the IStatementContainer's TileEntity seems to work instead, though, letting the logistics pipes gate triggers actually be added.

**Comment by loordgek** [comment]
https://www.google.nl/#q=github+squash+commits+pull+request

**Comment by noah13245678** [comment]
sorry if i'm being stupid here. Can I squash the commits without creating a new pull request, or does that need to be done by someone if they accept it?

**Comment by loordgek** [comment]
yes

How to squash commits

you can check out the repo in GitHub client, then open git shell from the client. run git rebase -i HEAD~<The number of commits to be squashed> and the commit squashing will be done. To push those changes, run git push -f, then you've finished squashing commits.

**Comment by davboecki** [comment]
@AEnterprise Thanks for the hint. Didn't know about that new feature of github.
@noah13245678 Thanks for the fix and the explanation.

**Pull request merged**
