### PR TITLE
Update mcmod.info

### PR DESCRIPTION
**Pull request by QORTEC**
Added Buildcraft Robotics Required Mods list (missing)
Added Buildcraft Robotics Dependencies

### CODE REVIEW

**Comment by QORTEC** [comment]
Fixes issue: #779

**Comment by nevercast** [comment]
Foolishly ran in to this issue on my server this afternoon as I don't have all modules installed and was under the impression that I'd be able to use Logistics Pipes entirely without the Robotics module.

**Comment by bziemons** [comment]
We rather need to have a separate proxy for BC Robotics, so it would not be a hard dependency. That's why I haven't merged yet.

**Comment by hron84** [comment]
@theZorro266 what if you add this dependency now and remove when proxy is done? Or robotics proxy is on the roadmap of the next release?

**Comment by davboecki** [comment]
That was what I intended to do...

**Pull request merged**
