### PR TITLE
ExpressionSink module

### PR DESCRIPTION
**Pull request by MrTJP**
sinks based on if the item name matches the typed expression.

Currently uses getFriedlyNameCC() to compare strings.  This can easily be swapped out with a better way in the future.

### CODE REVIEW

**Comment by MrTJP** [comment]
I want to know if nbt packets use unnecessary bandwidth.  Are they as efficient as a string packet?

**Comment by MrTJP** [comment]
This needs a texture by the way. I will make one later.

**Comment by davboecki** [comment]
Could you add an InfoBox to the Gui Like the Slot on the ModBased ItemSink module that will show the name the Server knows on the Client Gui. And could you rebase it.

**Comment by MrTJP** [comment]
What do you mean? Im not sure what u want me to show?

**Comment by davboecki** [comment]
When you use the ModBased ItemSink you can insert an item into the top left slot and the mod is shown on the right side. I would like to see something on the ExpressionSink Module as well but not as the input itself rather than as an info so the user can check what name an item has for the server.

**Comment by MrTJP** [comment]
There is no slot for items. The server name has to be the same as the client or it ruins the point of this module.

**Comment by AartBluestoke** [comment]
i think dav means a slot where you can put an item in, and get the server side name for it

**Comment by MrTJP** [comment]
Why would u need the server name?

**Comment by AartBluestoke** [comment]
because that is what your code uses -- the name of the item, as stored on the server. (either that or it uses the actual class name as a fallback)

**Comment by MrTJP** [comment]
yea, but the only reason you would want to see the server name is if it differs from the client name, which is not alright, since 2 items can have the same client names but different server names.  SO, it would make this module useless, because 2 items you may want to sink could have completely different server and client names.  

Unless by server name you mean getFriendlyNameCC() in which case it would be the same as the client name most of the time, but may be different sometimes, and thats why you would want to display the "server name" aka getFriendlyNameCC().

**Comment by GUIpsp** [comment]
@MrTJP Not everyone is english, you should add what dav requested.

**Comment by MrTJP** [comment]
i do plan on adding it. just don't have the time right now.

**Comment by AartBluestoke** [comment]
moderate code changes for the new multi-crafting branch merged, this commit will need a minor refactor to take it into account.

**Pull request closed without merging**
