### PR TITLE
Crafting Module - Updated

### PR DESCRIPTION
**Pull request by bbumblebee**

### CODE REVIEW

**Comment by AartBluestoke** [comment]
new code in dev allows active modules to exist and not stuff with passive networks (technically craters and satellite pipes are now pipes-with-modules, just that 99% of the logic is still in the pipe).

extra code is needed to allow active request queue's to be delivered to modules that process active requests.

**Comment by AartBluestoke** [comment]
new code has been merged which is a large part of allowing active modules, would you mind re-factoring this code for the current code branch?

**Comment by Flow86** [comment]
I definitly need a crafting module, please refactor and merge it soon ;-)

**Comment by davboecki** [comment]
It's not that easy. The crafting code still needs to be rewoked for this. It's not simply adding in a module.

**Pull request closed without merging**
