### PR TITLE
Fixed errors sometimes

### PR DESCRIPTION
**Pull request by miuirussia**
Error if open provider, that updated to new version

### CODE REVIEW

**Comment by GUIpsp** [comment]
How will canOpenGui ever throw?

**Comment by miuirussia** [comment]
If in provider class does not exist some classes

**Comment by miuirussia** [comment]
Example: 
if you don't have class: buildcraft.factory.TileAutoWorkbench. We get minecraft crash

**Comment by miuirussia** [comment]
Fixed mac backspace key

**Comment by GUIpsp** [comment]
@davboecki I wouldn't catch throawble, instead i'd catch something more specific.

**Comment by davboecki** [comment]
I'm thinking about using something like the proxyWrapper for most of the mod interaction stuff so for this as well, so i'm probably going to change it anyway.

**Comment by AartBluestoke** [comment]
I agree.. Certain exceptions should only be caught by coffee that can
handle it. Eg: interrupt exception, which can be injected when a shutdown
is requested, and put off memory exception. It is plausible that either
could come from within GUI handling code, and here is not the place to
silently ignore such conditions.

**Pull request merged**
