### PR TITLE
+ Thaumic AspectSink module

### PR DESCRIPTION
**Pull request by MrTJP**

### CODE REVIEW

**Comment by davboecki** [comment]
You are importing thaumcraft classes all over the place, even inside the ProxyManager. But what is, when there is no thaumcraft installed. Than the game would crash. Only access thaumcraft related classes inside the Thaumcraft Proxy not inside anything else. You need to write some sort of node Class/interface that can contain the Thaumcraft object in order to use that inside the module itself. Don't import anything from thaumcraft outside the proxy. If you need help contact me on IRC.

**Comment by MrTJP** [comment]
im assuming its similar to what is being done with the forestry proxy?  ill take a look once i have time, maybe in a few days or so.

**Comment by davboecki** [comment]
Ok looks good. Just for the DEBUG power addition: Also add a DEBUG check to the server packet handling to prevent cheating through modifyed clients.

**Comment by davboecki** [comment]
Oh and could you rebase this to the current Dev state so i can merge it without probelms.

EDIT:
Could you also change the background of the module to green so that it is an Sink module and not an extractor module.

**Comment by MrTJP** [comment]
Ok I will change the texture and server packet handler. Also, how do I check which files to rebase?

**Pull request closed without merging**
